// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: pinhole.proto

package stun

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求打洞协助消息
// 由客户端自己传递相关信息，因此可以向任意服务器请求STUN服务。
type Punches struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind  string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`    // 应用类型
	Addr  []byte `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`    // 公网地址（IP+Port）
	Level int32  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"` // NAT 层级（0: Pub/FullC; 1: RC; 2: P-RC; 3: Sym）
	Extra string `protobuf:"bytes,4,opt,name=extra,proto3" json:"extra,omitempty"`  // 额外信息（作为一种可能的灵活性），可选
}

func (x *Punches) Reset() {
	*x = Punches{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pinhole_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Punches) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Punches) ProtoMessage() {}

func (x *Punches) ProtoReflect() protoreflect.Message {
	mi := &file_pinhole_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Punches.ProtoReflect.Descriptor instead.
func (*Punches) Descriptor() ([]byte, []int) {
	return file_pinhole_proto_rawDescGZIP(), []int{0}
}

func (x *Punches) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Punches) GetAddr() []byte {
	if x != nil {
		return x.Addr
	}
	return nil
}

func (x *Punches) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Punches) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

var File_pinhole_proto protoreflect.FileDescriptor

var file_pinhole_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x69, 0x6e, 0x68, 0x6f, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x5d, 0x0a, 0x07, 0x50, 0x75, 0x6e, 0x63, 0x68, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69,
	0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x61, 0x64,
	0x64, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x78, 0x74, 0x72,
	0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x42, 0x09,
	0x5a, 0x07, 0x2e, 0x2e, 0x2f, 0x73, 0x74, 0x75, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_pinhole_proto_rawDescOnce sync.Once
	file_pinhole_proto_rawDescData = file_pinhole_proto_rawDesc
)

func file_pinhole_proto_rawDescGZIP() []byte {
	file_pinhole_proto_rawDescOnce.Do(func() {
		file_pinhole_proto_rawDescData = protoimpl.X.CompressGZIP(file_pinhole_proto_rawDescData)
	})
	return file_pinhole_proto_rawDescData
}

var file_pinhole_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pinhole_proto_goTypes = []interface{}{
	(*Punches)(nil), // 0: Punches
}
var file_pinhole_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pinhole_proto_init() }
func file_pinhole_proto_init() {
	if File_pinhole_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pinhole_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Punches); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pinhole_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pinhole_proto_goTypes,
		DependencyIndexes: file_pinhole_proto_depIdxs,
		MessageInfos:      file_pinhole_proto_msgTypes,
	}.Build()
	File_pinhole_proto = out.File
	file_pinhole_proto_rawDesc = nil
	file_pinhole_proto_goTypes = nil
	file_pinhole_proto_depIdxs = nil
}
