// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: stund.proto

package stun

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 打洞信息包
// 由服务器传递给请求UDP打洞的两个应用端节点。
// 也用于应用客户端向服务器递送自身的UDP节点信息。
// 方向（dir）：
// - master 主动打洞方，创建监听等待连入（server）。
// - slave 从动方，直接拨号连入（client）。
// - "" 客户端向服务器报送自己的用于打洞的UDP信息。
type Punchx struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dir           string                 `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"`      // 打洞方向（master|slave|""）
	Ip            []byte                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`        // 公网 IP
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`   // 公网端口（监听|通讯）
	Level         int32                  `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"` // NAT 层级（0: Pub/FullC; 1: RC; 2: P-RC; 3: Sym）
	Token         []byte                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`  // 验证标识（对端原样回传）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Punchx) Reset() {
	*x = Punchx{}
	mi := &file_stund_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Punchx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Punchx) ProtoMessage() {}

func (x *Punchx) ProtoReflect() protoreflect.Message {
	mi := &file_stund_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Punchx.ProtoReflect.Descriptor instead.
func (*Punchx) Descriptor() ([]byte, []int) {
	return file_stund_proto_rawDescGZIP(), []int{0}
}

func (x *Punchx) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *Punchx) GetIp() []byte {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *Punchx) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Punchx) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Punchx) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

// 服务器信息包
// 服务器接收到客户端的请求后，向客户端返回的信息。
// 可用于 STUN:Cone, STUN:Sym, STUN:Live 全部三个服务。
// 约束：
// UDP:IP地址与TCP链路相同，因此这里只需端口信息。
type ServInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          int32                  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`  // UDP 服务器端口
	Sn48          []byte                 `protobuf:"bytes,2,opt,name=sn48,proto3" json:"sn48,omitempty"`   // 随机序列号（48 bytes）
	Skey          []byte                 `protobuf:"bytes,3,opt,name=skey,proto3" json:"skey,omitempty"`   // 对称加密密钥
	Token         []byte                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"` // 密钥因子（需原样回传）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServInfo) Reset() {
	*x = ServInfo{}
	mi := &file_stund_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServInfo) ProtoMessage() {}

func (x *ServInfo) ProtoReflect() protoreflect.Message {
	mi := &file_stund_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServInfo.ProtoReflect.Descriptor instead.
func (*ServInfo) Descriptor() ([]byte, []int) {
	return file_stund_proto_rawDescGZIP(), []int{1}
}

func (x *ServInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServInfo) GetSn48() []byte {
	if x != nil {
		return x.Sn48
	}
	return nil
}

func (x *ServInfo) GetSkey() []byte {
	if x != nil {
		return x.Skey
	}
	return nil
}

func (x *ServInfo) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

// LiveNAT 消息包
// 包含客户端提供的目标UDP地址和序列号。
// 序列号之前会前置一个批次字节，以方便客户端辨别发送的时间段。
type LiveNAT struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sn49          []byte                 `protobuf:"bytes,1,opt,name=sn49,proto3" json:"sn49,omitempty"`  // 批次+序列号（1+48字节）
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"` // 公网端口
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveNAT) Reset() {
	*x = LiveNAT{}
	mi := &file_stund_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveNAT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveNAT) ProtoMessage() {}

func (x *LiveNAT) ProtoReflect() protoreflect.Message {
	mi := &file_stund_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveNAT.ProtoReflect.Descriptor instead.
func (*LiveNAT) Descriptor() ([]byte, []int) {
	return file_stund_proto_rawDescGZIP(), []int{2}
}

func (x *LiveNAT) GetSn49() []byte {
	if x != nil {
		return x.Sn49
	}
	return nil
}

func (x *LiveNAT) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// Hosto NewHost协助消息
// 记载客户端UDP信息，在TCP链路上请求对端协助。
type Hosto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            []byte                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`      // 公网IP
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"` // 端口
	Sn48          []byte                 `protobuf:"bytes,3,opt,name=sn48,proto3" json:"sn48,omitempty"`  // 序列号（48字节）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hosto) Reset() {
	*x = Hosto{}
	mi := &file_stund_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hosto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hosto) ProtoMessage() {}

func (x *Hosto) ProtoReflect() protoreflect.Message {
	mi := &file_stund_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hosto.ProtoReflect.Descriptor instead.
func (*Hosto) Descriptor() ([]byte, []int) {
	return file_stund_proto_rawDescGZIP(), []int{3}
}

func (x *Hosto) GetIp() []byte {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *Hosto) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Hosto) GetSn48() []byte {
	if x != nil {
		return x.Sn48
	}
	return nil
}

// UDPInfo 客户端UDP信息
// 服务器在 STUN:Cone|Sym 中向客户端告知其UDP状况。
type UDPInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            []byte                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`      // UDP 公网IP
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"` // UDP 公网端口
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UDPInfo) Reset() {
	*x = UDPInfo{}
	mi := &file_stund_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UDPInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UDPInfo) ProtoMessage() {}

func (x *UDPInfo) ProtoReflect() protoreflect.Message {
	mi := &file_stund_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UDPInfo.ProtoReflect.Descriptor instead.
func (*UDPInfo) Descriptor() ([]byte, []int) {
	return file_stund_proto_rawDescGZIP(), []int{4}
}

func (x *UDPInfo) GetIp() []byte {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *UDPInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// PunchOne 定向打洞信息
// 如果未指定目标，表示当前节点为登记。
// 登记时 expire 字段有效，最大值为30分钟（30*60秒），
// - 负值表示遵照服务器内置默认值（30分钟）。
// - 零值表示立即过期（但可使用一次）。
type PunchOne struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Client        *Punchx                `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`  // 客户端自身的信息
	Target        *UDPInfo               `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`  // 目标节点的UDP信息
	Expire        int32                  `protobuf:"varint,3,opt,name=expire,proto3" json:"expire,omitempty"` // 登记暂存时长（秒数）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PunchOne) Reset() {
	*x = PunchOne{}
	mi := &file_stund_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PunchOne) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PunchOne) ProtoMessage() {}

func (x *PunchOne) ProtoReflect() protoreflect.Message {
	mi := &file_stund_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PunchOne.ProtoReflect.Descriptor instead.
func (*PunchOne) Descriptor() ([]byte, []int) {
	return file_stund_proto_rawDescGZIP(), []int{5}
}

func (x *PunchOne) GetClient() *Punchx {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *PunchOne) GetTarget() *UDPInfo {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *PunchOne) GetExpire() int32 {
	if x != nil {
		return x.Expire
	}
	return 0
}

var File_stund_proto protoreflect.FileDescriptor

const file_stund_proto_rawDesc = "" +
	"\n" +
	"\vstund.proto\"j\n" +
	"\x06Punchx\x12\x10\n" +
	"\x03dir\x18\x01 \x01(\tR\x03dir\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\fR\x02ip\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x14\n" +
	"\x05level\x18\x05 \x01(\x05R\x05level\x12\x14\n" +
	"\x05token\x18\x04 \x01(\fR\x05token\"\\\n" +
	"\bServInfo\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x05R\x04port\x12\x12\n" +
	"\x04sn48\x18\x02 \x01(\fR\x04sn48\x12\x12\n" +
	"\x04skey\x18\x03 \x01(\fR\x04skey\x12\x14\n" +
	"\x05token\x18\x04 \x01(\fR\x05token\"1\n" +
	"\aLiveNAT\x12\x12\n" +
	"\x04sn49\x18\x01 \x01(\fR\x04sn49\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\"?\n" +
	"\x05Hosto\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\fR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x12\n" +
	"\x04sn48\x18\x03 \x01(\fR\x04sn48\"-\n" +
	"\aUDPInfo\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\fR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\"e\n" +
	"\bPunchOne\x12\x1f\n" +
	"\x06client\x18\x01 \x01(\v2\a.PunchxR\x06client\x12 \n" +
	"\x06target\x18\x02 \x01(\v2\b.UDPInfoR\x06target\x12\x16\n" +
	"\x06expire\x18\x03 \x01(\x05R\x06expireB\tZ\a../stunb\x06proto3"

var (
	file_stund_proto_rawDescOnce sync.Once
	file_stund_proto_rawDescData []byte
)

func file_stund_proto_rawDescGZIP() []byte {
	file_stund_proto_rawDescOnce.Do(func() {
		file_stund_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stund_proto_rawDesc), len(file_stund_proto_rawDesc)))
	})
	return file_stund_proto_rawDescData
}

var file_stund_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_stund_proto_goTypes = []any{
	(*Punchx)(nil),   // 0: Punchx
	(*ServInfo)(nil), // 1: ServInfo
	(*LiveNAT)(nil),  // 2: LiveNAT
	(*Hosto)(nil),    // 3: Hosto
	(*UDPInfo)(nil),  // 4: UDPInfo
	(*PunchOne)(nil), // 5: PunchOne
}
var file_stund_proto_depIdxs = []int32{
	0, // 0: PunchOne.client:type_name -> Punchx
	4, // 1: PunchOne.target:type_name -> UDPInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_stund_proto_init() }
func file_stund_proto_init() {
	if File_stund_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stund_proto_rawDesc), len(file_stund_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stund_proto_goTypes,
		DependencyIndexes: file_stund_proto_depIdxs,
		MessageInfos:      file_stund_proto_msgTypes,
	}.Build()
	File_stund_proto = out.File
	file_stund_proto_goTypes = nil
	file_stund_proto_depIdxs = nil
}
