// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: newhost.proto

package node

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 客户端UDP信息
// 注：将在 TCP 链路上传输（而非UDP）。
type ClientUDP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip   []byte `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`      // 公网IP
	Port int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"` // 端口（UDP）
	Sn32 []byte `protobuf:"bytes,3,opt,name=sn32,proto3" json:"sn32,omitempty"`  // 序列号（32字节）
}

func (x *ClientUDP) Reset() {
	*x = ClientUDP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_newhost_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientUDP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientUDP) ProtoMessage() {}

func (x *ClientUDP) ProtoReflect() protoreflect.Message {
	mi := &file_newhost_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientUDP.ProtoReflect.Descriptor instead.
func (*ClientUDP) Descriptor() ([]byte, []int) {
	return file_newhost_proto_rawDescGZIP(), []int{0}
}

func (x *ClientUDP) GetIp() []byte {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *ClientUDP) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ClientUDP) GetSn32() []byte {
	if x != nil {
		return x.Sn32
	}
	return nil
}

var File_newhost_proto protoreflect.FileDescriptor

var file_newhost_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6e, 0x65, 0x77, 0x68, 0x6f, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x43, 0x0a, 0x09, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x55, 0x44, 0x50, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x6e, 0x33, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x73, 0x6e, 0x33, 0x32, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2e, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_newhost_proto_rawDescOnce sync.Once
	file_newhost_proto_rawDescData = file_newhost_proto_rawDesc
)

func file_newhost_proto_rawDescGZIP() []byte {
	file_newhost_proto_rawDescOnce.Do(func() {
		file_newhost_proto_rawDescData = protoimpl.X.CompressGZIP(file_newhost_proto_rawDescData)
	})
	return file_newhost_proto_rawDescData
}

var file_newhost_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_newhost_proto_goTypes = []interface{}{
	(*ClientUDP)(nil), // 0: ClientUDP
}
var file_newhost_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_newhost_proto_init() }
func file_newhost_proto_init() {
	if File_newhost_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_newhost_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientUDP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_newhost_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_newhost_proto_goTypes,
		DependencyIndexes: file_newhost_proto_depIdxs,
		MessageInfos:      file_newhost_proto_msgTypes,
	}.Build()
	File_newhost_proto = out.File
	file_newhost_proto_rawDesc = nil
	file_newhost_proto_goTypes = nil
	file_newhost_proto_depIdxs = nil
}
