// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: basic.proto

package base

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Proto 通用数据包
// 用于封装其它proto编码数据，但同时提供类型标识。
type Proto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          int32                  `protobuf:"varint,1,opt,name=name,proto3" json:"name,omitempty"` // 指令名
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`  // 关联数据（待解码）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proto) Reset() {
	*x = Proto{}
	mi := &file_basic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proto) ProtoMessage() {}

func (x *Proto) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proto.ProtoReflect.Descriptor instead.
func (*Proto) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{0}
}

func (x *Proto) GetName() int32 {
	if x != nil {
		return x.Name
	}
	return 0
}

func (x *Proto) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Kind 节点声明类别
// 如果节点仅需NAT探测而无需打洞服务，name可以任意设置，但base需合法。
// 因为NAT探测是标准服务，无需类型区分。
// base:
// - depots     数据驿站类型
// - blockchain 区块链节点类型
// - app        应用节点类型
// - findings   发现节点类型
// seek:
// 客户端向服务器寻求的服务。
// - find:net   参与组网（仅适用 findings，UDP）
// - find:help  寻求上线协助（获取 Findings 公网节点，适用 UDP & TCP）
// - app:kinds  获取服务器支持的应用名清单（UDP & TCP）
// - app:serv   获取服务器暂存的TCP应用服务节点（TCP）
// - nat:cone   请求NAT类型探测服务（UDP）
// - nat:live   请求NAT映射存活期探测服务（UDP）
// - app:punch  请求UDP打洞协助&信令协调（UDP）
// - peer:tcp   登记为可直连的TCP服务器（对应 app:serv 目标）
type Kind struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          string                 `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"` // 基础名称（depots|blockchain|app|findings）
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // 具体的应用名称（……）
	Seek          string                 `protobuf:"bytes,3,opt,name=seek,proto3" json:"seek,omitempty"` // 寻求的服务（find:net|find:help|app:kinds|app:serv|...）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kind) Reset() {
	*x = Kind{}
	mi := &file_basic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kind) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kind) ProtoMessage() {}

func (x *Kind) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kind.ProtoReflect.Descriptor instead.
func (*Kind) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{1}
}

func (x *Kind) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *Kind) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Kind) GetSeek() string {
	if x != nil {
		return x.Seek
	}
	return ""
}

// Stake 服务器收益账户
// 公共服务节点向应用节点提供的信息，以获取可能有的奖励/捐赠。
type Stake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`     // 收益地址（区块链）
	Member        string                 `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"` // 服务节点标识（群成员，通常也为区块链地址）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stake) Reset() {
	*x = Stake{}
	mi := &file_basic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stake) ProtoMessage() {}

func (x *Stake) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stake.ProtoReflect.Descriptor instead.
func (*Stake) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{2}
}

func (x *Stake) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Stake) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

// NodeInfo 节点信息
// 每一个节点都应有的信息，表达自身所属应用的类型。
// type:
// 对应 Kind 中的 base 和 name，中间以冒号（:）分隔。
// spki:
// 用于节点间通过自签名证书创建安全连接（SPKI指纹验证）。
// natt:
// - 0: Blocked     UDP 阻塞
// - 1: Pub/FullC   公网或FullC
// - 2: RC          受限
// - 3: P-RC        端口受限
// - 4: Firewalled  UDP 防火墙（可主动打洞）
// - 5: Sym         对称（不可打洞）
type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`       // 节点类型：depots:x | blockchain:x | app:x | findings:x
	Network       string                 `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"` // 网络类型：tcp | udp
	Ip            []byte                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`           // IP地址（IPv4/IPv6，公网）
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`      // 端口号（NAT 公网映射）
	Natt          int32                  `protobuf:"varint,6,opt,name=natt,proto3" json:"natt,omitempty"`      // NAT类型：Pub/FullC | RC | ...
	Spki          []byte                 `protobuf:"bytes,7,opt,name=spki,proto3" json:"spki,omitempty"`       // 证书的公钥编码哈希（SPKI）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_basic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{3}
}

func (x *NodeInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NodeInfo) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *NodeInfo) GetIp() []byte {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *NodeInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *NodeInfo) GetNatt() int32 {
	if x != nil {
		return x.Natt
	}
	return 0
}

func (x *NodeInfo) GetSpki() []byte {
	if x != nil {
		return x.Spki
	}
	return nil
}

var File_basic_proto protoreflect.FileDescriptor

const file_basic_proto_rawDesc = "" +
	"\n" +
	"\vbasic.proto\"/\n" +
	"\x05Proto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\x05R\x04name\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"B\n" +
	"\x04Kind\x12\x12\n" +
	"\x04base\x18\x01 \x01(\tR\x04base\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04seek\x18\x03 \x01(\tR\x04seek\"3\n" +
	"\x05Stake\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x16\n" +
	"\x06member\x18\x02 \x01(\tR\x06member\"\x84\x01\n" +
	"\bNodeInfo\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\anetwork\x18\x02 \x01(\tR\anetwork\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\fR\x02ip\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x12\n" +
	"\x04natt\x18\x06 \x01(\x05R\x04natt\x12\x12\n" +
	"\x04spki\x18\a \x01(\fR\x04spkiB\tZ\a../baseb\x06proto3"

var (
	file_basic_proto_rawDescOnce sync.Once
	file_basic_proto_rawDescData []byte
)

func file_basic_proto_rawDescGZIP() []byte {
	file_basic_proto_rawDescOnce.Do(func() {
		file_basic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_basic_proto_rawDesc), len(file_basic_proto_rawDesc)))
	})
	return file_basic_proto_rawDescData
}

var file_basic_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_basic_proto_goTypes = []any{
	(*Proto)(nil),    // 0: Proto
	(*Kind)(nil),     // 1: Kind
	(*Stake)(nil),    // 2: Stake
	(*NodeInfo)(nil), // 3: NodeInfo
}
var file_basic_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_basic_proto_init() }
func file_basic_proto_init() {
	if File_basic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_basic_proto_rawDesc), len(file_basic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_basic_proto_goTypes,
		DependencyIndexes: file_basic_proto_depIdxs,
		MessageInfos:      file_basic_proto_msgTypes,
	}.Build()
	File_basic_proto = out.File
	file_basic_proto_goTypes = nil
	file_basic_proto_depIdxs = nil
}
