// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: basic.proto

package base

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Proto 通用数据包
// 用于封装其它proto编码数据，但同时提供类型标识。
type Proto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          int32                  `protobuf:"varint,1,opt,name=name,proto3" json:"name,omitempty"` // 指令名
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`  // 关联数据（待解码）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proto) Reset() {
	*x = Proto{}
	mi := &file_basic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proto) ProtoMessage() {}

func (x *Proto) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proto.ProtoReflect.Descriptor instead.
func (*Proto) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{0}
}

func (x *Proto) GetName() int32 {
	if x != nil {
		return x.Name
	}
	return 0
}

func (x *Proto) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 节点声明类别
// 如果节点仅需NAT探测而无需打洞服务，name可以任意设置，但base需合法。
// 因为NAT探测是标准内置服务，无需类型区分。
// seek: 寻求的服务，仅在客户端向服务器请求时有用。
// - find:net 参与组网，仅适用 findings 类型
// - assist:x 寻求上线协助（获取Finder节点，仅使用 findings 类型）
// - kind:app 获取服务器支持的应用名清单
// - app:serv 请求NAT探测、打洞协助或获取TCP服务节点
// - peer:tcp 登记为可直连TCP服务器，后续提供node.Peer（直接node.EncodePeer编码）
type Kind struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          string                 `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"` // 基础名称（depots|blockchain|app|findings）
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // 具体的服务名称（……）
	Seek          string                 `protobuf:"bytes,3,opt,name=seek,proto3" json:"seek,omitempty"` // 寻求的服务（find:net|assist:x|kind:app|app:serv|peer:tcp）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kind) Reset() {
	*x = Kind{}
	mi := &file_basic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kind) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kind) ProtoMessage() {}

func (x *Kind) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kind.ProtoReflect.Descriptor instead.
func (*Kind) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{1}
}

func (x *Kind) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *Kind) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Kind) GetSeek() string {
	if x != nil {
		return x.Seek
	}
	return ""
}

// 服务类型名集
// 服务器返回给应用端的信息（此时seek无效）。
type ServKinds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []*Kind                `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServKinds) Reset() {
	*x = ServKinds{}
	mi := &file_basic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServKinds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServKinds) ProtoMessage() {}

func (x *ServKinds) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServKinds.ProtoReflect.Descriptor instead.
func (*ServKinds) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{2}
}

func (x *ServKinds) GetNames() []*Kind {
	if x != nil {
		return x.Names
	}
	return nil
}

// 收益信息
// 用于公共服务节点获取应用端的捐赠。
// 其中ID用于群组个体分辨，实际上也可以直接是区块链地址。
type Stake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`     // 身份标识
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"` // 收益地址（区块链）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stake) Reset() {
	*x = Stake{}
	mi := &file_basic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stake) ProtoMessage() {}

func (x *Stake) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stake.ProtoReflect.Descriptor instead.
func (*Stake) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{3}
}

func (x *Stake) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Stake) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

// 节点信息
// 每一个在线节点都应当有的信息（UDP）。
// type 中冒号前的部分为基础类型名称，冒号后的 xx 部分为具体应用的名称。
// SPKI 用于自签名证书的公钥哈希验证。
type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // 节点类型：depots:xx | blockchain:xx | app:xx | findings:xx
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"` // 地址：IP:Port（NAT映射）
	Nat           string                 `protobuf:"bytes,3,opt,name=nat,proto3" json:"nat,omitempty"`   // NAT类型：Pub/FullC | RC | P-RC | Sym
	Spki          []byte                 `protobuf:"bytes,4,opt,name=spki,proto3" json:"spki,omitempty"` // 自签证书的公钥编码哈希（SPKI）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_basic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{4}
}

func (x *NodeInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NodeInfo) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *NodeInfo) GetNat() string {
	if x != nil {
		return x.Nat
	}
	return ""
}

func (x *NodeInfo) GetSpki() []byte {
	if x != nil {
		return x.Spki
	}
	return nil
}

var File_basic_proto protoreflect.FileDescriptor

const file_basic_proto_rawDesc = "" +
	"\n" +
	"\vbasic.proto\"/\n" +
	"\x05Proto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\x05R\x04name\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"B\n" +
	"\x04Kind\x12\x12\n" +
	"\x04base\x18\x01 \x01(\tR\x04base\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04seek\x18\x03 \x01(\tR\x04seek\"(\n" +
	"\tServKinds\x12\x1b\n" +
	"\x05names\x18\x01 \x03(\v2\x05.KindR\x05names\"+\n" +
	"\x05Stake\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\"X\n" +
	"\bNodeInfo\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x10\n" +
	"\x03nat\x18\x03 \x01(\tR\x03nat\x12\x12\n" +
	"\x04spki\x18\x04 \x01(\fR\x04spkiB\tZ\a../baseb\x06proto3"

var (
	file_basic_proto_rawDescOnce sync.Once
	file_basic_proto_rawDescData []byte
)

func file_basic_proto_rawDescGZIP() []byte {
	file_basic_proto_rawDescOnce.Do(func() {
		file_basic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_basic_proto_rawDesc), len(file_basic_proto_rawDesc)))
	})
	return file_basic_proto_rawDescData
}

var file_basic_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_basic_proto_goTypes = []any{
	(*Proto)(nil),     // 0: Proto
	(*Kind)(nil),      // 1: Kind
	(*ServKinds)(nil), // 2: ServKinds
	(*Stake)(nil),     // 3: Stake
	(*NodeInfo)(nil),  // 4: NodeInfo
}
var file_basic_proto_depIdxs = []int32{
	1, // 0: ServKinds.names:type_name -> Kind
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_basic_proto_init() }
func file_basic_proto_init() {
	if File_basic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_basic_proto_rawDesc), len(file_basic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_basic_proto_goTypes,
		DependencyIndexes: file_basic_proto_depIdxs,
		MessageInfos:      file_basic_proto_msgTypes,
	}.Build()
	File_basic_proto = out.File
	file_basic_proto_goTypes = nil
	file_basic_proto_depIdxs = nil
}
